[package]
name = "model"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
async-trait = "0.1"
derive_more = { version = "0", default-features = false, features = [ "error" ] }
json-patch = "0.2"
# k8s-openapi must match the version required by kube and enable a k8s version feature
k8s-openapi = { version = "0.13.0", default-features = false, features = ["v1_20"] }
kube = { version = "0.59.0", default-features = false, features = [ "derive", "jsonpatch", "client" ] }
lazy_static = "1"
log = "0.4"
maplit = "1.0.2"
regex = "1"
schemars = "0.8"
serde = { version = "1", features = [ "derive" ] }
serde_json = "1"
serde_plain = "1"
snafu = "0.6"

[dev-dependencies]
selftest = { path = "../selftest" }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }

[features]
# The `integ` feature enables integration tests. These tests require docker and kind.
integ = []
