[package]
name = "selftest"
version = "0.1.0"
edition = "2018"


[dependencies]
anyhow = "1"
futures = "0.3.8"
k8s-openapi = { version = "0.13.0", default-features = false, features = ["v1_20"] }
kube = { version = "0.59.0", default-features = true }
model = { path = "../model"}
tempfile = "3"
tokio = { version = "1", features = [ "time" ] }
