[package]
name = "selftest"
version = "0.1.0"
edition = "2021"


[dependencies]
anyhow = "1"
envy = "0"
futures = "0.3.8"
k8s-openapi = { version = "0", default-features = false, features = ["v1_20"] }
kube = { version = "0.64", default-features = true }
lazy_static = "1"
model = { path = "../model"}
serde = "1"
tempfile = "3"
tokio = { version = "1", features = [ "time" ] }
