[package]
name = "bottlerocket-types"
version = "0.0.1"
edition = "2018"
publish = false
license = "MIT OR Apache-2.0"

[dependencies]
model = { version = "0.0.1", path = "../../model" }
serde = "1"
serde_plain = "1"
