---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: testsys
  name: testsys-bottlerocket-aws
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubernetes.io/service-account.name: testsys-test-agent-account
  name: testsys-test-agent-account
  namespace: testsys-bottlerocket-aws
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: testsys-agent-role
  namespace: testsys-bottlerocket-aws
rules:
  - apiGroups:
      - testsys.bottlerocket.aws
    resources:
      - tests
      - tests/status
    verbs:
      - get
      - list
      - patch
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: testsys-agent-role-binding
  namespace: testsys-bottlerocket-aws
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: testsys-agent-role
subjects:
  - kind: ServiceAccount
    name: testsys-test-agent-account
    namespace: testsys-bottlerocket-aws
