apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: "{{cluster-name}}"
  version: "{{version}}"
  region: "{{region}}"
kubernetesNetworkConfig:
  ipFamily: IPv4
vpc:
  clusterEndpoints:
    publicAccess: true
    privateAccess: true
iam:
  withOIDC: true
  serviceRoleARN: arn:aws:iam::<account-id>:role/eksctl-x86-64-aws-k8s-124-test-cluster-ServiceRole-...
iamIdentityMappings:
  - arn: arn:aws:iam::<account-id>:role/testsysAdministratorRole
    groups:
      - system:masters
    username: admin
    noDuplicateARNs: true
addons:
  - name: vpc-cni
    version: latest
  - name: coredns
    version: latest
  - name: kube-proxy
    version: latest
nodeGroups:
    - name: empty
      desiredCapacity: 0
      iam:
        instanceRoleARN: "arn:aws:iam::<account-id>:role/eksctl-x86-64-aws-k8s-124-test-cl-NodeInstanceRole-..."
        instanceProfileARN: "arn:aws:iam::<account-id>:instance-profile/eksctl-x86-64-aws-k8s-124-test-cluster-nodegroup-ng-4a91f189-NodeInstanceProfile-..."
