[package]
name = "yamlgen"
version = "0.1.0"
edition = "2021"
publish = false

[build-dependencies]
kube = { version = "0.64", default-features = false }
model = { path = "../model" }
serde_yaml = "0"
