[package]
name = "yamlgen"
version = "0.1.0"
edition = "2021"
publish = false
license = "MIT OR Apache-2.0"

[build-dependencies]
kube = { version = "0.71", default-features = false }
model = { path = "../model" }
serde_yaml = "0"
