[package]
name = "yamlgen"
version = "0.1.0"
edition = "2018"
publish = false

[build-dependencies]
client = { path = "../client" }
kube = { version = "0.59.0", default-features = false, features = ["client", "rustls-tls"] }
serde_yaml = "0.8"
