[package]
name = "agent-common"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
#derive_more = { version = "0", default-features = false, features = ["error"] }
model = { path = "../../model" }
snafu = "0.6"

[dev-dependencies]
tempfile = "3"
