name: Build
on:
  pull_request:
    paths-ignore:
      - '**.md'
      - 'design/**'
      - 'tools/**'
      - '.github/dependabot.yml'
  push:
    paths-ignore:
      - '**.md'
      - 'design/**'
      - 'tools/**'
      - '.github/dependabot.yml'
    branches: [develop]
jobs:
  build:
    runs-on: [self-hosted, linux, x64]
    steps:
      - uses: actions/checkout@v3
      - run: rustup default 1.61.0
      - run: make build
        # If we forget to add yamlgen changes to our commits, this will fail.
      - name: ensure that git is clean
        run: test -z "$(git status --untracked-files=all --porcelain)"
      - run: make controller
      - run: make duplicator-resource-agent
      - run: make example-resource-agent
      - run: make example-test-agent
      - run: make integ-test
        env:
          TESTSYS_SELFTEST_SKIP_IMAGE_BUILDS: true
          TESTSYS_SELFTEST_THREADS: 1
  images:
    runs-on: [ self-hosted, linux, x64 ]
    steps:
      - uses: actions/checkout@v3
      - run: make images
  license-check:
    # A small machine is OK for this independent job.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup default 1.61.0
      - run: make cargo-deny
