name: Images
on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    paths-ignore:
      - '**.md'
    branches: [develop]
jobs:
  build-images:
    strategy:
      matrix:
        make_target:
         - "controller-image"
         - "example-resource-agent-image"
         - "example-test-agent-image"
         - "sonobuoy-test-agent-image"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make ${{ matrix.make_target }}
